"""
Walkthrough 2: Learning from Failure and Adapting
=================================================
From Chapter 14 (The Cognitive Loop in Practice)

User prompt: "Calculate the optimal portfolio allocation for
these 5 stocks based on their historical returns and covariances,
minimizing risk for a target return of 8%."

This walkthrough demonstrates the failure-diagnosis-learning cycle:
the system attempts neural reasoning, fails, diagnoses the failure
via meta-cognition, switches strategy to code generation + sandbox
execution, succeeds, and stores the lesson for future use.
"""

import numpy as np
from scipy.optimize import minimize


# ---------------------------------------------------------------
# Attempt 1: Neural Reasoning (Fails)
# ---------------------------------------------------------------
# Layer 7 assesses the task and selects a reasoning strategy.

TRACE_ASSESSMENT = """
[T+0ms] Layer 7 -> assess_task()
Difficulty: HARD (keyword "optimal", math optimization)
Strategy: "reason_then_verify"
Model: DeepSeek-R1
"""

# The reasoning model attempts to solve the quadratic program
# analytically. It produces weights: [0.35, 0.25, 0.20, 0.15, 0.05].

TRACE_VERIFICATION_FAIL = """
[T+18s] Layer 3 -> Symbolic verification

Z3 checks:
  Constraint 1: weights sum to 1.0  -> 1.0  PASS
  Constraint 2: all weights >= 0    ->      PASS
  Constraint 3: expected return >= 8%
                -> computed: 7.2%            FAIL
  Constraint 4: risk is minimized
                -> cannot verify             UNKNOWN

Verification: REFUTED
Detail: "Portfolio return is 7.2%, below target of 8.0%.
         Constraint 3 violated."
"""
# NOTE: The Neural Precision Trap -- LLMs are excellent at
# generating the *form* of a mathematical solution but unreliable
# at computing exact numerical values.


# ---------------------------------------------------------------
# Meta-Cognitive Diagnosis
# ---------------------------------------------------------------

TRACE_DIAGNOSIS = """
[T+19s] Layer 7 -> MetaCognition.diagnose_failure()

Failure analysis:
  What failed:   Constraint satisfaction (return target)
  Why it failed: Neural reasoning generated approximate
                 weights rather than solving the actual
                 quadratic program
  Failure class: "mathematical_precision"
  Confidence that retry with same strategy succeeds: 0.15

Strategy recommendation: SWITCH to "compute_then_verify"
  Rationale: This is a well-defined optimization problem
  with a known solver approach. The reasoning model
  should generate CODE that solves it, not attempt to
  solve it directly.
"""


# ---------------------------------------------------------------
# Attempt 2: Code Generation + Sandbox (Succeeds)
# ---------------------------------------------------------------
# The planner replans. Task 3 becomes code generation + execution.
# This is the only RUNNABLE code block in the chapter.

# Generated by DeepSeek-R1 -- mean-variance optimization
returns = np.array([0.12, 0.10, 0.08, 0.07, 0.05])

# BUG NOTE: The book uses `np.array([...])` with ellipsis for the
# covariance matrix. Below is a plausible symmetric positive-definite
# covariance matrix for demonstration purposes.
cov_matrix = np.array([
    [0.04, 0.006, 0.002, 0.001, 0.0005],
    [0.006, 0.03, 0.004, 0.002, 0.001],
    [0.002, 0.004, 0.02, 0.003, 0.0015],
    [0.001, 0.002, 0.003, 0.015, 0.002],
    [0.0005, 0.001, 0.0015, 0.002, 0.01],
])
target_return = 0.08


def portfolio_risk(weights):
    return np.sqrt(weights @ cov_matrix @ weights)


constraints = [
    {'type': 'eq',
     'fun': lambda w: np.sum(w) - 1.0},
    {'type': 'ineq',
     'fun': lambda w: w @ returns - target_return},
]
bounds = [(0, 1) for _ in range(5)]

result = minimize(
    portfolio_risk, x0=np.ones(5) / 5,
    method='SLSQP', bounds=bounds,
    constraints=constraints,
)


TRACE_SANDBOX_OUTPUT = """
[T+24s] Sandbox output: [0.2847, 0.3012, 0.1956,
                          0.1423, 0.0762]

[T+26s] Z3 checks:
  Constraint 1: sum = 1.0000    PASS
  Constraint 2: all >= 0        PASS
  Constraint 3: return = 8.003% PASS
  Constraint 4: risk = 12.4%    PASS (verified as
                                 local minimum)

Verification: VERIFIED
Confidence: 0.94
"""


# ---------------------------------------------------------------
# Learning Phase
# ---------------------------------------------------------------
# The system does not just succeed -- it stores the lesson.

TRACE_LEARNING = """
[T+27.5s] Layer 7 -> extract_lesson()

Lesson: "Numerical optimization problems should be
solved via code generation and sandbox execution, not
via direct neural reasoning. Use the
'compute_then_verify' strategy for any task involving
constrained optimization."

[T+28s] EpisodicMemory.store(Episode{
    task: "Constrained portfolio optimization",
    actions: [
      "Attempted neural reasoning -> FAILED",
      "Replanned to code generation + sandbox",
      "Generated scipy optimization -> SUCCEEDED",
      "Verified all constraints via Z3"
    ],
    outcome: "success",
    lesson: "Numerical optimization -> code generation",
    importance: 0.9
})

[T+28.5s] _strategy_scores updated:
    "math_optimization" -> {
      "reason_then_verify": [False],
      "compute_then_verify": [True]
    }
"""


# ---------------------------------------------------------------
# The Payoff: Next Time
# ---------------------------------------------------------------
# When the system encounters a similar task in a future session:

TRACE_FUTURE_SESSION = """
# Future session, similar task

[T+0ms] Layer 7 -> assess_task(
    "Optimize delivery routes for 20 warehouses"
)
[T+200ms] EpisodicMemory.recall("optimization problem")
Result: Episode{lesson: "Numerical optimization ->
        code generation, not neural reasoning"}

[T+300ms] select_strategy("math_optimization")
  Historical: reason_then_verify -> 0% success
              compute_then_verify -> 100%
  Selected: "compute_then_verify"

# Skips the failed first attempt entirely.
# Saves ~10 seconds and ~5,000 tokens.
"""

# ---------------------------------------------------------------
# Cost Comparison: Without vs. With Learning
# ---------------------------------------------------------------
# Metric        | First encounter   | With episodic memory
# Attempts      | 2                 | 1
# Wall time     | 28.5s             | ~14s
# Total tokens  | ~18,000           | ~9,000
# Cost          | ~$0.032           | ~$0.016
# Confidence    | 0.94              | 0.94
#
# INSIGHT: Cross-Session Learning Without Gradient Updates
# The frozen model did not change -- the system's behavior
# changed because its episodic memory and strategy scores did.
# The lesson persists because it lives in Qdrant, not in a
# context window.


if __name__ == "__main__":
    print("=== Walkthrough 2: Mean-Variance Portfolio Optimization ===")
    print(f"Optimal weights: {result.x}")
    print(f"Sum of weights:  {result.x.sum():.4f}")
    print(f"Expected return: {result.x @ returns:.4%}")
    print(f"Portfolio risk:  {portfolio_risk(result.x):.4%}")
    print(f"Optimization success: {result.success}")
